/* global React */

// Polilabs — Landing page. Two-stage hero:
//
//   1. headline — "Accelerating policy research." slides in from the
//                 right edge with an accelerating cubic-bezier and
//                 exits off the left edge over ~3 seconds. Single
//                 line, no wrap.
//   2. diagram  — once the headline has exited, an SVG diagram fades
//                 in node-by-node showing one bill (S. 4664, the DOE
//                 AI Act) connected to two of its real defined terms
//                 and two of its real external statute citations.
//                 Color encodes node TYPE — bill, definition,
//                 external citation — not chamber. Sits free on the
//                 cream canvas (no border, no panel).
//
// Below the hero: by-the-numbers (with each number linking to its
// primary source), how-it-works, corpus aggregates, CTA reprise.
//
// Data comes from web-design-a/landing-graph.json, regenerated by
// scripts/build_landing_graph.py — including the `hero` block with
// the focused diagram's real corpus connections.

const { useState, useEffect, useRef } = React;

// ── TypedHeadline ──────────────────────────────────────────────────────
// "Accelerating policy research." types out one character at a time at
// a constant cadence (~85ms per character). Single line — the font
// size is clamped in CSS so the phrase never wraps. After typing
// completes, the cursor lingers briefly, then onDone fires so the
// hero can swap in the diagram stage.
function TypedHeadline({ text, onDone, charMs = 85, holdMs = 750 }) {
  const [shown, setShown] = useState(0);
  const onDoneRef = useRef(onDone);
  onDoneRef.current = onDone;
  const fired = useRef(false);

  useEffect(() => {
    if (shown < text.length) {
      const id = setTimeout(() => setShown(shown + 1), charMs);
      return () => clearTimeout(id);
    }
    if (!fired.current) {
      fired.current = true;
      const id = setTimeout(() => {
        onDoneRef.current && onDoneRef.current();
      }, holdMs);
      return () => clearTimeout(id);
    }
  }, [shown, text.length, charMs, holdMs]);

  const done = shown >= text.length;
  return (
    <h1 className="land-typed-h">
      <span className="land-typed-text">{text.slice(0, shown)}</span>
      <span className={"land-typed-caret " + (done ? "is-done" : "")} aria-hidden="true">|</span>
    </h1>
  );
}

// ── HeroDiagram ────────────────────────────────────────────────────────
// Small four-node subgraph of the corpus:
//
//                                  ○  "foundation model"   ┌───────────┐
//                                       (definition) ──────│ def text  │
//                                  ╲                       └───────────┘
//                                   ╲ defines
//                                    ╲
//   ●─────────────────────────────────●  S. 4664
//   S. 4178                            (Dept of Energy AI Act)
//   (related bill,                    ╱
//    shares definitions)             ╱  section
//                                   ╱                      ┌───────────┐
//                                  ●  Sec. 7 ──────────────│ excerpt   │
//                                                          └───────────┘
//
// Nodes are small circular blobs; bills are filled navy, definitions
// amber, sections sage. Two of the right-side nodes carry floating
// description cards holding real corpus content (definition text /
// section excerpt). Edge labels: "defines", "section". The bill-to-
// bill edge is unlabeled; the shared term legend below the diagram
// names what they have in common.
function HeroDiagram({ hero, width = 1080, height = 560 }) {
  const [step, setStep] = useState(0); // 0 = nothing; 1..5 = nodes; 6 = cards
  useEffect(() => {
    if (!hero) return;
    const cues = [120, 320, 540, 760, 980, 1180];
    const timers = cues.map((t, i) => setTimeout(() => setStep(i + 1), t));
    return () => timers.forEach(clearTimeout);
  }, [hero]);

  if (!hero || !hero.center) {
    return <div className="land-diagram-empty mono">corpus unavailable</div>;
  }

  const W = width, H = height;

  // ── hand-placed node positions (slightly asymmetric for natural feel)
  const nCenter = { x: 470, y: 305, r: 26, kind: "bill" };
  const nRelated = { x: 175, y: 280, r: 20, kind: "bill" };
  const nDef = { x: 720, y: 165, r: 18, kind: "def" };
  const nSec = { x: 710, y: 430, r: 18, kind: "sec" };

  // floating description cards (anchored to the right-side nodes)
  const cardDef = { x: 800, y: 70,  w: 270, h: 165 };
  const cardSec = { x: 790, y: 380, w: 270, h: 140 };

  // labels per node
  const lblCenter = hero.center.ref;
  const lblRelated = hero.related.ref;
  const lblDef = `"${hero.featured_definition.term}"`;
  const lblSec = "Sec. " + (hero.featured_section ? "7" : "?");

  // The script trims the "(N) Term" preface; here we additionally
  // strip the "The term <X> means " prefix and capitalize what
  // remains so the card reads as a fluent gloss instead of repeating
  // the term's own name.
  const defText = (() => {
    const raw = (hero.featured_definition.text || "").trim();
    const trimmed = raw.replace(/^The term [a-zA-Z ]+? means\s+/i, "");
    return trimmed.charAt(0).toUpperCase() + trimmed.slice(1);
  })();
  const secText = (hero.featured_section?.text || "").trim();

  const sponsorClean = (s) => (s || "").replace(/\s*\[[^\]]+\]\s*/, " ").trim();

  // edge geometry: stop at the circle perimeter, not the center
  const edge = (a, b) => {
    const dx = b.x - a.x, dy = b.y - a.y;
    const L = Math.hypot(dx, dy) || 1;
    const ux = dx / L, uy = dy / L;
    return {
      x1: a.x + ux * a.r,
      y1: a.y + uy * a.r,
      x2: b.x - ux * b.r,
      y2: b.y - uy * b.r,
      mx: (a.x + b.x) / 2,
      my: (a.y + b.y) / 2,
    };
  };
  const eRelated = edge(nRelated, nCenter);
  const eDef     = edge(nCenter, nDef);
  const eSec     = edge(nCenter, nSec);
  // leader lines from definition/section nodes to their cards
  const leaderDef = { x1: nDef.x + nDef.r * 0.7, y1: nDef.y - 4, x2: cardDef.x, y2: cardDef.y + 20 };
  const leaderSec = { x1: nSec.x + nSec.r * 0.7, y1: nSec.y + 4, x2: cardSec.x, y2: cardSec.y + 20 };

  // Wrap a string into multi-line tspans (≤ width characters per line).
  const tspans = (text, x, startY, lineH, maxChars, maxLines) => {
    const lines = wrapText(text, maxChars);
    const shown = lines.slice(0, maxLines);
    if (lines.length > maxLines && shown.length) {
      const last = shown[shown.length - 1];
      shown[shown.length - 1] = last.slice(0, maxChars - 1).replace(/\s+\S*$/, "") + "…";
    }
    return shown.map((line, i) => (
      <tspan key={i} x={x} y={startY + i * lineH}>{line}</tspan>
    ));
  };

  // ── render ────────────────────────────────────────────────────────
  const nodeOn = (i) => step >= i;
  const edgesOn = step >= 5;
  const cardsOn = step >= 6;

  return (
    <div className="land-diagram-wrap">
      <svg
        className="land-diagram"
        viewBox={`0 0 ${W} ${H}`}
        preserveAspectRatio="xMidYMid meet"
        role="img"
        aria-label={`Knowledge graph excerpt: ${hero.center.ref} and one related bill, ${hero.related.ref}.`}
      >
        {/* edges */}
        <g className={"land-edges " + (edgesOn ? "is-on" : "")}>
          <line className="land-edge-line" {...eRelated} />
          <line className="land-edge-line" {...eDef} />
          <line className="land-edge-line" {...eSec} />
          {/* edge labels — only the typed ones, sketch-style */}
          <text className="land-edge-label mono"
                x={eDef.mx + 14} y={eDef.my - 4} textAnchor="start">defines</text>
          <text className="land-edge-label mono"
                x={eSec.mx + 14} y={eSec.my + 12} textAnchor="start">section</text>
        </g>

        {/* leader lines from right-side nodes to their cards */}
        <g className={"land-leaders " + (cardsOn ? "is-on" : "")}>
          <line className="land-leader-line" {...leaderDef} />
          <line className="land-leader-line" {...leaderSec} />
        </g>

        {/* nodes — small circular blobs */}
        <g className={"land-node land-node-bill " + (nodeOn(1) ? "is-on" : "")}>
          <circle cx={nCenter.x} cy={nCenter.y} r={nCenter.r} className="land-blob" />
          <text x={nCenter.x} y={nCenter.y + nCenter.r + 18}
                textAnchor="middle" className="land-blob-label">
            {lblCenter}
          </text>
          <text x={nCenter.x} y={nCenter.y + nCenter.r + 34}
                textAnchor="middle" className="land-blob-sub mono">
            {hero.center.label.slice(0, 36)}
          </text>
        </g>

        <g className={"land-node land-node-bill " + (nodeOn(2) ? "is-on" : "")}>
          <circle cx={nRelated.x} cy={nRelated.y} r={nRelated.r} className="land-blob" />
          <text x={nRelated.x} y={nRelated.y + nRelated.r + 18}
                textAnchor="middle" className="land-blob-label">
            {lblRelated}
          </text>
          <text x={nRelated.x} y={nRelated.y + nRelated.r + 34}
                textAnchor="middle" className="land-blob-sub mono">
            related bill
          </text>
        </g>

        <g className={"land-node land-node-def " + (nodeOn(3) ? "is-on" : "")}>
          <circle cx={nDef.x} cy={nDef.y} r={nDef.r} className="land-blob" />
          <text x={nDef.x} y={nDef.y + nDef.r + 16}
                textAnchor="middle" className="land-blob-label-italic">
            {lblDef}
          </text>
        </g>

        <g className={"land-node land-node-sec " + (nodeOn(4) ? "is-on" : "")}>
          <circle cx={nSec.x} cy={nSec.y} r={nSec.r} className="land-blob" />
          <text x={nSec.x} y={nSec.y + nSec.r + 16}
                textAnchor="middle" className="land-blob-label">
            {lblSec}
          </text>
        </g>

        {/* floating description cards */}
        <g className={"land-card " + (cardsOn ? "is-on" : "")}>
          <rect
            x={cardDef.x} y={cardDef.y}
            width={cardDef.w} height={cardDef.h}
            rx={6} className="land-card-rect"
          />
          <text x={cardDef.x + 12} y={cardDef.y + 18}
                className="land-card-head mono">DEFINITION · {hero.center.ref}</text>
          <text x={cardDef.x + 12} y={cardDef.y + 36}
                className="land-card-title">{lblDef}</text>
          <text className="land-card-body">
            {tspans(defText, cardDef.x + 12, cardDef.y + 60, 14, 36, 7)}
          </text>
        </g>

        <g className={"land-card " + (cardsOn ? "is-on" : "")}>
          <rect
            x={cardSec.x} y={cardSec.y}
            width={cardSec.w} height={cardSec.h}
            rx={6} className="land-card-rect"
          />
          <text x={cardSec.x + 12} y={cardSec.y + 18}
                className="land-card-head mono">SECTION · {hero.center.ref}</text>
          <text x={cardSec.x + 12} y={cardSec.y + 36}
                className="land-card-title">{hero.featured_section?.heading || ""}</text>
          <text className="land-card-body">
            {tspans(secText, cardSec.x + 12, cardSec.y + 60, 14, 36, 5)}
          </text>
        </g>
      </svg>

      <div className="land-diagram-legend mono">
        <span><b>{hero.center.ref}</b> · {sponsorClean(hero.center.sponsor)}</span>
        <span className="leg-sep">·</span>
        <span>related to <b>{hero.related.ref}</b> via shared term{hero.shared_terms.length > 1 ? "s" : ""} <em>{hero.shared_terms.slice(0, 2).join(", ")}</em></span>
      </div>
    </div>
  );
}

// Wrap a string into ≤ width characters per line, breaking at word
// boundaries. Tiny helper so the SVG node text fits inside its box.
function wrapText(s, width) {
  const words = String(s || "").split(/\s+/);
  const lines = [];
  let cur = "";
  for (const w of words) {
    if (!cur) { cur = w; continue; }
    if ((cur + " " + w).length <= width) cur += " " + w;
    else { lines.push(cur); cur = w; }
  }
  if (cur) lines.push(cur);
  // limit to 3 lines max with ellipsis on the last one
  if (lines.length > 3) {
    const head = lines.slice(0, 2);
    let tail = lines.slice(2).join(" ");
    if (tail.length > width - 1) tail = tail.slice(0, width - 1) + "…";
    return [...head, tail];
  }
  return lines;
}

// ── Stat tile (unchanged from v2) ────────────────────────────────────
function Stat({ n, body, source, href, caveat }) {
  return (
    <div className="land-stat">
      <a
        className="land-stat-n"
        href={href}
        target="_blank"
        rel="noopener noreferrer"
        title={`Source: ${source}`}
        aria-label={`${n}. ${body} Source: ${source}.`}
      >
        <span className="land-stat-n-text">{n}</span>
        <span className="land-stat-arrow" aria-hidden="true">↗</span>
      </a>
      <div className="land-stat-body">{body}</div>
      {caveat && <div className="land-stat-caveat mono">{caveat}</div>}
    </div>
  );
}

function Pillar({ title, body }) {
  return (
    <div className="land-pillar">
      <div className="land-pillar-title">{title}</div>
      <p className="land-pillar-body">{body}</p>
    </div>
  );
}

// ── Landing ──────────────────────────────────────────────────────────────
function Landing({ user, onOpenWorkspace, onSignIn, onSignOut }) {
  const [graphData, setGraphData] = useState(null);
  const [hero, setHero] = useState(null);
  const [corpus, setCorpus] = useState(null);
  const [loadError, setLoadError] = useState(false);

  // Hero stage machine: 'headline' → 'fading' (300ms) → 'diagram'.
  // The headline disappears completely; the diagram's own internal
  // stagger then reveals each node in turn.
  const [stage, setStage] = useState("headline");

  useEffect(() => {
    let cancelled = false;
    fetch("landing-graph.json")
      .then((r) => {
        if (!r.ok) throw new Error(`HTTP ${r.status}`);
        return r.json();
      })
      .then((j) => {
        if (cancelled) return;
        setGraphData(j.graph);
        setHero(j.hero);
        setCorpus(j.corpus);
      })
      .catch(() => { if (!cancelled) setLoadError(true); });
    return () => { cancelled = true; };
  }, []);

  const c = corpus || { bills: 191, sections: 29616, defined_terms: 1241, external_citations: 646 };

  return (
    <div className="land">
      <header className="land-header">
        <div className="land-brand">polilabs</div>
        <nav className="land-nav">
          {user ? (
            <React.Fragment>
              <span className="land-user mono">{user.email}</span>
              <button type="button" className="land-link" onClick={onSignOut}>
                Sign out
              </button>
            </React.Fragment>
          ) : (
            <button type="button" className="land-link" onClick={onSignIn}>
              Sign in
            </button>
          )}
        </nav>
      </header>

      <main className="land-main">
        {/* HERO — sliding headline → SVG anatomy diagram */}
        <section className={"land-hero land-hero-stage-" + stage}>
          {(stage === "headline" || stage === "fading") && (
            <div className={"land-typed-wrap " + (stage === "fading" ? "is-fading" : "")}>
              <TypedHeadline
                text="Accelerating policy research."
                onDone={() => {
                  setStage("fading");
                  setTimeout(() => setStage("diagram"), 380);
                }}
              />
            </div>
          )}

          {stage === "diagram" && (
            <div className="land-stage">
              <div className="land-diagram-container">
                {hero ? (
                  <HeroDiagram hero={hero} />
                ) : (
                  <div className="land-diagram-empty mono">
                    {loadError ? "graph data unavailable" : "loading corpus…"}
                  </div>
                )}
              </div>
              <p className="land-lede">
                Citation-accurate research instrument for U.S. federal
                AI-governance legislation. Every answer grounded in
                verbatim bill text. If it is not in the bill, polilabs
                does not say it.
              </p>
              <div className="land-cta-row">
                <button type="button" className="land-cta" onClick={onOpenWorkspace}>
                  Open the workspace <span aria-hidden="true">→</span>
                </button>
                <div className="land-corpus mono">
                  <b>{c.bills}</b>&nbsp;bills
                  <span className="land-dot">·</span>
                  <b>118th–119th</b>&nbsp;Congress
                </div>
              </div>
            </div>
          )}
        </section>

        {/* BY THE NUMBERS — each number is itself the source link */}
        <section className="land-section land-stats-section">
          <div className="land-section-label mono">
            <span>By the numbers</span>
            <span className="land-section-tag mono">
              click any figure for the primary source
            </span>
          </div>
          <div className="land-stats-grid">
            <Stat
              n="19,315"
              body="bills introduced in the 118th Congress; 3% became law."
              source="GovTrack, Statistics and Historical Comparison"
              href="https://www.govtrack.us/congress/bills/statistics"
            />
            <Stat
              n="9×"
              body="denser legislation per enacted law than in 1955."
              source="Brookings Vital Statistics on Congress, via Pew (2021)"
              href="https://www.pewresearch.org/short-reads/2021/01/21/nothing-lame-about-this-lame-duck-116th-congress-had-busiest-post-election-session-in-recent-history/"
            />
            <Stat
              n="34%"
              body="of legal queries hallucinated by Westlaw's AI-Assisted Research, despite vendor 'hallucination-free' claims."
              source="Magesh et al., Hallucination-Free? Stanford RegLab, J. Empirical Legal Studies 2024"
              href="https://dho.stanford.edu/wp-content/uploads/Legal_RAG_Hallucinations.pdf"
            />
            <Stat
              n="3.1 yrs"
              body="median Hill-staff tenure — roughly a third haven't served a full Congress."
              source="New America / Congressional Capacity Survey, 2021 (2019 data)"
              href="https://www.newamerica.org/insights/congressional-brain-drain/congressional-staffers-job-satisfaction-career-trajectories-and-compensation/"
            />
            <Stat
              n="84%"
              body="of senior Hill staff: 'we can't accomplish as much as we'd like.'"
              source="Congressional Management Foundation, State of the Congress 2024"
              href="https://www.congressfoundation.org/s/cmf-state-of-the-congress-2024.pdf"
              caveat="n = 138, 5% response rate"
            />
            <Stat
              n="$34 : $1"
              body="corporate vs. labor + public-interest lobbying ratio."
              source="Drutman, The Business of America is Lobbying (Oxford, 2015); summary at New America"
              href="https://www.newamerica.org/insights/there-wasnt-always-much-corporate-lobbying/"
              caveat="2015 figures"
            />
            <Stat
              n="150+"
              body="AI bills introduced in the 118th Congress; zero became law."
              source="Brennan Center for Justice, AI Legislation Tracker (2025)"
              href="https://www.brennancenter.org/our-work/research-reports/artificial-intelligence-legislation-tracker"
            />
            <Stat
              n="½"
              body="House committee staff today versus 1980, as policy complexity has grown."
              source="R Street / Drutman coalition letter (2015)"
              href="https://www.rstreet.org/commentary/congress-must-invest-in-its-own-capacity-again/"
            />
          </div>
        </section>

        {/* HOW IT WORKS */}
        <section className="land-section">
          <div className="land-section-label mono">
            <span>How it works</span>
          </div>
          <div className="land-pillars">
            <Pillar
              title="Mechanically extracted"
              body="Definitions, amendments, and citations are pulled from the bill XML directly. No model paraphrases the law before you read it."
            />
            <Pillar
              title="Verbatim text, synced"
              body="Click a citation; the matching span lights up in the bill text. If the substring can't be located, the highlight degrades to scroll — it never invents one."
            />
            <Pillar
              title="Honest unknowns"
              body="If the corpus does not contain an answer, polilabs says so. No paraphrase, no inference, no plausible-sounding completion."
            />
          </div>
        </section>

        {/* WHAT'S IN THE CORPUS */}
        <section className="land-section">
          <div className="land-section-label mono">
            <span>What's in the corpus</span>
            <span className="land-section-tag mono">v1 · 118th–119th Congress</span>
          </div>
          <div className="land-corpus-grid">
            <div className="land-corpus-cell">
              <b>{c.bills.toLocaleString()}</b>
              <span>bills</span>
            </div>
            <div className="land-corpus-cell">
              <b>{c.sections.toLocaleString()}</b>
              <span>sections</span>
            </div>
            <div className="land-corpus-cell">
              <b>{c.defined_terms.toLocaleString()}</b>
              <span>defined terms</span>
            </div>
            <div className="land-corpus-cell">
              <b>{c.external_citations.toLocaleString()}</b>
              <span>external citations</span>
            </div>
          </div>
        </section>

        {/* CTA REPRISE */}
        <section className="land-cta-band">
          <div className="land-cta-band-copy">
            <div className="land-cta-band-h">Open the corpus.</div>
            <div className="land-cta-band-sub">
              Ask a question. Read what the bill actually says.
            </div>
          </div>
          <button type="button" className="land-cta" onClick={onOpenWorkspace}>
            Open the workspace <span aria-hidden="true">→</span>
          </button>
        </section>

        <footer className="land-foot">
          <span className="mono">
            polilabs · {c.bills} bills · 118th–119th Congress · citation-accurate, no hallucination
          </span>
        </footer>
      </main>
    </div>
  );
}

window.Landing = Landing;
