/* global React */

// Polilabs — Landing page. Two-stage hero:
//
//   1. headline — "Accelerating policy research." slides in from the
//                 right edge with an accelerating cubic-bezier and
//                 exits off the left edge over ~3 seconds. Single
//                 line, no wrap.
//   2. diagram  — once the headline has exited, an SVG diagram fades
//                 in node-by-node showing one bill (S. 4664, the DOE
//                 AI Act) connected to two of its real defined terms
//                 and two of its real external statute citations.
//                 Color encodes node TYPE — bill, definition,
//                 external citation — not chamber. Sits free on the
//                 cream canvas (no border, no panel).
//
// Below the hero: by-the-numbers (with each number linking to its
// primary source), how-it-works, corpus aggregates, CTA reprise.
//
// Data comes from web-design-a/landing-graph.json, regenerated by
// scripts/build_landing_graph.py — including the `hero` block with
// the focused diagram's real corpus connections.

const { useState, useEffect, useRef } = React;

// ── TypedHeadline ──────────────────────────────────────────────────────
// "Accelerating policy research." types out one character at a time at
// a constant cadence (~85ms per character). Single line — the font
// size is clamped in CSS so the phrase never wraps. After typing
// completes, the cursor lingers briefly, then onDone fires so the
// hero can swap in the diagram stage.
function TypedHeadline({ text, onDone, charMs = 85, holdMs = 750 }) {
  const [shown, setShown] = useState(0);
  const onDoneRef = useRef(onDone);
  onDoneRef.current = onDone;
  const fired = useRef(false);

  useEffect(() => {
    if (shown < text.length) {
      const id = setTimeout(() => setShown(shown + 1), charMs);
      return () => clearTimeout(id);
    }
    if (!fired.current) {
      fired.current = true;
      const id = setTimeout(() => {
        onDoneRef.current && onDoneRef.current();
      }, holdMs);
      return () => clearTimeout(id);
    }
  }, [shown, text.length, charMs, holdMs]);

  const done = shown >= text.length;
  return (
    <h1 className="land-typed-h">
      <span className="land-typed-text">{text.slice(0, shown)}</span>
      <span className={"land-typed-caret " + (done ? "is-done" : "")} aria-hidden="true">|</span>
    </h1>
  );
}

// ── HeroDiagram ────────────────────────────────────────────────────────
// Stripe-inspired soft scene: glowing dots and a drifting particle
// field on a warm-cool gradient backdrop. Cursor-reactive — particles
// within a small radius of the pointer gently displace.
//
// Same corpus subgraph as before (S. 4178 ↔ S. 4664 ↔ "foundation
// model" / Sec. 7) but rendered as luminous nodes with minimal text
// labels (no long content cards). The connection structure is the
// point; the per-node text lives in the workspace, not the hero.
function HeroDiagram({ hero }) {
  const containerRef = useRef(null);
  const canvasRef = useRef(null);
  // Reveal stage drives both node visibility and the staggered label
  // fade-in. Total reveal arc: ~5 seconds, like the user asked.
  //   0: empty
  //   1: related node    (0.4s)
  //   2: related↔center edge   (1.0s)
  //   3: center node     (1.6s)
  //   4: center↔def edge       (2.4s)
  //   5: def node        (3.0s)
  //   6: center↔sec edge       (3.8s)
  //   7: sec node        (4.4s)
  const [step, setStep] = useState(0);
  const [size, setSize] = useState({ w: 1200, h: 560 });

  // size-track the container so the canvas always fills the section
  useEffect(() => {
    if (!containerRef.current) return;
    const ro = new ResizeObserver((entries) => {
      for (const e of entries) {
        setSize({
          w: Math.max(360, Math.round(e.contentRect.width)),
          h: Math.max(360, Math.round(e.contentRect.height)),
        });
      }
    });
    ro.observe(containerRef.current);
    return () => ro.disconnect();
  }, []);

  // Sequenced reveal — every cue is ~600–800 ms apart so the diagram
  // builds itself in front of the reader, one note then one edge at
  // a time, instead of popping in all at once.
  useEffect(() => {
    if (!hero) return;
    const cues = [400, 1000, 1600, 2400, 3000, 3800, 4400];
    const timers = cues.map((t, i) => setTimeout(() => setStep(i + 1), t));
    return () => timers.forEach(clearTimeout);
  }, [hero]);

  // node/edge data + drag state lives in a ref so the RAF loop sees
  // current values without re-binding the effect every render.
  const sceneRef = useRef(null);

  useEffect(() => {
    if (!hero || !canvasRef.current) return;
    const W = size.w, H = size.h;
    const cvs = canvasRef.current;
    const dpr = window.devicePixelRatio || 1;
    cvs.width = W * dpr;
    cvs.height = H * dpr;
    cvs.style.width = W + "px";
    cvs.style.height = H + "px";
    const ctx = cvs.getContext("2d");
    ctx.scale(dpr, dpr);

    // hand-placed positions, tuned for breathing room at ≥1024 wide
    const cx = W / 2, cy = H / 2;
    const span = Math.min(380, W * 0.30);
    const mains = [
      { id: "related", x: cx - span * 1.0,  y: cy + 8,             r: 7,   color: "#1e3fa8" },
      { id: "center",  x: cx,                y: cy,                 r: 11,  color: "#1e3fa8" },
      { id: "def",     x: cx + span * 0.75,  y: cy - span * 0.45,   r: 6.5, color: "#b45309" },
      { id: "sec",     x: cx + span * 0.75,  y: cy + span * 0.45,   r: 6.5, color: "#2f6b2c" },
    ];
    const links = [
      { a: "related", b: "center", step: 2, label: null },
      { a: "center",  b: "def",    step: 4, label: "defines" },
      { a: "center",  b: "sec",    step: 6, label: "section" },
    ];

    sceneRef.current = { mains, links, drag: null };

    // ── drag interaction (Obsidian-style — released nodes stay put) ─
    const nearest = (mx, my) => {
      let best = null, bestD = 22 * 22;
      for (const m of mains) {
        const dx = mx - m.x, dy = my - m.y;
        const d2 = dx * dx + dy * dy;
        if (d2 < bestD) { bestD = d2; best = m; }
      }
      return best;
    };
    const onDown = (ev) => {
      const rect = cvs.getBoundingClientRect();
      const mx = ev.clientX - rect.left;
      const my = ev.clientY - rect.top;
      const m = nearest(mx, my);
      if (m) {
        sceneRef.current.drag = { node: m, ox: mx - m.x, oy: my - m.y };
        cvs.setPointerCapture?.(ev.pointerId);
        cvs.style.cursor = "grabbing";
        ev.preventDefault();
      }
    };
    const onMove = (ev) => {
      const rect = cvs.getBoundingClientRect();
      const mx = ev.clientX - rect.left;
      const my = ev.clientY - rect.top;
      const sc = sceneRef.current;
      if (sc.drag) {
        sc.drag.node.x = mx - sc.drag.ox;
        sc.drag.node.y = my - sc.drag.oy;
      } else {
        cvs.style.cursor = nearest(mx, my) ? "grab" : "default";
      }
    };
    const onUp = () => {
      if (sceneRef.current.drag) {
        sceneRef.current.drag = null;
        cvs.style.cursor = "default";
      }
    };
    cvs.addEventListener("pointerdown", onDown);
    cvs.addEventListener("pointermove", onMove);
    cvs.addEventListener("pointerup", onUp);
    cvs.addEventListener("pointercancel", onUp);

    // ── render loop ──────────────────────────────────────────────────
    let raf = 0;
    const draw = () => {
      ctx.clearRect(0, 0, W, H);
      const { mains: M, links: L } = sceneRef.current;
      const cur = step;

      // edges first — thin straight strokes; appear at their cue step
      for (const l of L) {
        if (cur < l.step) continue;
        const A = M.find((m) => m.id === l.a);
        const B = M.find((m) => m.id === l.b);
        // alpha fades in over ~400ms after the cue (handled by CSS
        // class transitions on labels; for canvas we just draw at full)
        ctx.strokeStyle = "rgba(30, 35, 50, 0.30)";
        ctx.lineWidth = 1;
        ctx.beginPath();
        ctx.moveTo(A.x, A.y);
        ctx.lineTo(B.x, B.y);
        ctx.stroke();

        if (l.label) {
          ctx.font = '11px "JetBrains Mono", ui-monospace, monospace';
          ctx.fillStyle = "rgba(80, 75, 70, 0.6)";
          ctx.textAlign = "left";
          ctx.textBaseline = "middle";
          const lx = (A.x + B.x) / 2 + 8;
          const ly = (A.y + B.y) / 2 - 8;
          ctx.fillText(l.label, lx, ly);
        }
      }

      // nodes — solid filled circles, no halo
      const nodeAppearsAt = { related: 1, center: 3, def: 5, sec: 7 };
      for (const m of M) {
        if (cur < nodeAppearsAt[m.id]) continue;
        ctx.fillStyle = m.color;
        ctx.beginPath();
        ctx.arc(m.x, m.y, m.r, 0, Math.PI * 2);
        ctx.fill();
        // thin darker border for crispness on the cream background
        ctx.strokeStyle = "rgba(0, 0, 0, 0.18)";
        ctx.lineWidth = 1;
        ctx.stroke();
      }

      // expose node positions for HTML label tracking
      window.__landNodePos = M.reduce((acc, m) => {
        acc[m.id] = { x: m.x, y: m.y, r: m.r };
        return acc;
      }, {});

      raf = requestAnimationFrame(draw);
    };
    raf = requestAnimationFrame(draw);

    return () => {
      cancelAnimationFrame(raf);
      cvs.removeEventListener("pointerdown", onDown);
      cvs.removeEventListener("pointermove", onMove);
      cvs.removeEventListener("pointerup", onUp);
      cvs.removeEventListener("pointercancel", onUp);
    };
  }, [hero, size.w, size.h, step]);

  if (!hero || !hero.center) {
    return <div className="land-diagram-empty mono">corpus unavailable</div>;
  }

  // Static label coords match the baseline node positions. Labels
  // fade in alongside their dots using the step state.
  const cx = size.w / 2, cy = size.h / 2;
  const span = Math.min(380, size.w * 0.30);
  const labels = [
    { id: "related", appear: 1, x: cx - span * 1.0,  y: cy + 8 + 24,
      text: hero.related.ref, sub: "related bill" },
    { id: "center",  appear: 3, x: cx,                y: cy + 28,
      text: hero.center.ref,  sub: hero.center.label.slice(0, 36) },
    { id: "def",     appear: 5, x: cx + span * 0.75,  y: cy - span * 0.45 + 24,
      text: `"${hero.featured_definition.term}"`, sub: "definition", italic: true },
    { id: "sec",     appear: 7, x: cx + span * 0.75,  y: cy + span * 0.45 + 24,
      text: "Sec. 7", sub: "section" },
  ];

  return (
    <div ref={containerRef} className="land-scene">
      <canvas ref={canvasRef} className="land-scene-canvas" />
      <div className="land-scene-labels">
        {labels.map((l) => (
          <div
            key={l.id}
            className={"lbl " + (step >= l.appear ? "is-on" : "")}
            style={{ left: l.x, top: l.y }}
          >
            <div className={"lbl-text " + (l.italic ? "lbl-italic" : "")}>
              {l.text}
            </div>
            <div className="lbl-sub mono">{l.sub}</div>
          </div>
        ))}
      </div>
    </div>
  );
}

// ── Stat tile (unchanged from v2) ────────────────────────────────────
function Stat({ n, body, source, href, caveat }) {
  return (
    <div className="land-stat">
      <a
        className="land-stat-n"
        href={href}
        target="_blank"
        rel="noopener noreferrer"
        title={`Source: ${source}`}
        aria-label={`${n}. ${body} Source: ${source}.`}
      >
        <span className="land-stat-n-text">{n}</span>
        <span className="land-stat-arrow" aria-hidden="true">↗</span>
      </a>
      <div className="land-stat-body">{body}</div>
      {caveat && <div className="land-stat-caveat mono">{caveat}</div>}
    </div>
  );
}

function Pillar({ title, body }) {
  return (
    <div className="land-pillar">
      <div className="land-pillar-title">{title}</div>
      <p className="land-pillar-body">{body}</p>
    </div>
  );
}

// ── Landing ──────────────────────────────────────────────────────────────
function Landing({ user, onOpenWorkspace, onSignIn, onSignOut }) {
  const [graphData, setGraphData] = useState(null);
  const [hero, setHero] = useState(null);
  const [corpus, setCorpus] = useState(null);
  const [loadError, setLoadError] = useState(false);

  // Hero stage machine: 'headline' → 'fading' (300ms) → 'diagram'.
  // The headline disappears completely; the diagram's own internal
  // stagger then reveals each node in turn.
  const [stage, setStage] = useState("headline");

  useEffect(() => {
    let cancelled = false;
    fetch("landing-graph.json")
      .then((r) => {
        if (!r.ok) throw new Error(`HTTP ${r.status}`);
        return r.json();
      })
      .then((j) => {
        if (cancelled) return;
        setGraphData(j.graph);
        setHero(j.hero);
        setCorpus(j.corpus);
      })
      .catch(() => { if (!cancelled) setLoadError(true); });
    return () => { cancelled = true; };
  }, []);

  const c = corpus || { bills: 191, sections: 29616, defined_terms: 1241, external_citations: 646 };

  return (
    <div className="land">
      <header className="land-header">
        <div className="land-brand">polilabs</div>
        <nav className="land-nav">
          {user ? (
            <React.Fragment>
              <span className="land-user mono">{user.email}</span>
              <button type="button" className="land-link" onClick={onSignOut}>
                Sign out
              </button>
            </React.Fragment>
          ) : (
            <button type="button" className="land-link" onClick={onSignIn}>
              Sign in
            </button>
          )}
        </nav>
      </header>

      {/* HERO — headline stage. Lives outside .land-main so the
          headline can sit in the cream canvas and the diagram zone
          below (also outside .land-main) is naturally full-width. */}
      <section className={"land-hero land-hero-stage-" + stage}>
        {(stage === "headline" || stage === "fading") && (
          <div className={"land-typed-wrap " + (stage === "fading" ? "is-fading" : "")}>
            <TypedHeadline
              text="Accelerating policy research."
              onDone={() => {
                setStage("fading");
                setTimeout(() => setStage("diagram"), 380);
              }}
            />
          </div>
        )}
      </section>

      {/* DIAGRAM ZONE — full-bleed direct child of .land. No max-width,
          no calc tricks. Mounts only after the headline has exited. */}
      {stage === "diagram" && (
        <section className="land-diagram-zone">
          {hero ? (
            <HeroDiagram hero={hero} />
          ) : (
            <div className="land-diagram-empty mono">
              {loadError ? "graph data unavailable" : "loading corpus…"}
            </div>
          )}
        </section>
      )}

      {/* Lede + CTA — sits below the diagram zone, still wrapped in
          the constrained container so it doesn't run viewport-wide. */}
      {stage === "diagram" && (
        <section className="land-below">
          <p className="land-lede">
            Citation-accurate research instrument for U.S. federal
            AI-governance legislation. Every answer grounded in
            verbatim bill text. If it is not in the bill, polilabs
            does not say it.
          </p>
          <div className="land-cta-row">
            <button type="button" className="land-cta" onClick={onOpenWorkspace}>
              Open the workspace <span aria-hidden="true">→</span>
            </button>
            <div className="land-corpus mono">
              <b>{c.bills}</b>&nbsp;bills
              <span className="land-dot">·</span>
              <b>118th–119th</b>&nbsp;Congress
            </div>
          </div>
        </section>
      )}

      <main className="land-main">
        {/* BY THE NUMBERS — each number is itself the source link */}
        <section className="land-section land-stats-section">
          <div className="land-section-label mono">
            <span>By the numbers</span>
            <span className="land-section-tag mono">
              click any figure for the primary source
            </span>
          </div>
          <div className="land-stats-grid">
            <Stat
              n="19,315"
              body="bills introduced in the 118th Congress; 3% became law."
              source="GovTrack, Statistics and Historical Comparison"
              href="https://www.govtrack.us/congress/bills/statistics"
            />
            <Stat
              n="9×"
              body="denser legislation per enacted law than in 1955."
              source="Brookings Vital Statistics on Congress, via Pew (2021)"
              href="https://www.pewresearch.org/short-reads/2021/01/21/nothing-lame-about-this-lame-duck-116th-congress-had-busiest-post-election-session-in-recent-history/"
            />
            <Stat
              n="34%"
              body="of legal queries hallucinated by Westlaw's AI-Assisted Research, despite vendor 'hallucination-free' claims."
              source="Magesh et al., Hallucination-Free? Stanford RegLab, J. Empirical Legal Studies 2024"
              href="https://dho.stanford.edu/wp-content/uploads/Legal_RAG_Hallucinations.pdf"
            />
            <Stat
              n="3.1 yrs"
              body="median Hill-staff tenure — roughly a third haven't served a full Congress."
              source="New America / Congressional Capacity Survey, 2021 (2019 data)"
              href="https://www.newamerica.org/insights/congressional-brain-drain/congressional-staffers-job-satisfaction-career-trajectories-and-compensation/"
            />
            <Stat
              n="84%"
              body="of senior Hill staff: 'we can't accomplish as much as we'd like.'"
              source="Congressional Management Foundation, State of the Congress 2024"
              href="https://www.congressfoundation.org/s/cmf-state-of-the-congress-2024.pdf"
              caveat="n = 138, 5% response rate"
            />
            <Stat
              n="$34 : $1"
              body="corporate vs. labor + public-interest lobbying ratio."
              source="Drutman, The Business of America is Lobbying (Oxford, 2015); summary at New America"
              href="https://www.newamerica.org/insights/there-wasnt-always-much-corporate-lobbying/"
              caveat="2015 figures"
            />
            <Stat
              n="150+"
              body="AI bills introduced in the 118th Congress; zero became law."
              source="Brennan Center for Justice, AI Legislation Tracker (2025)"
              href="https://www.brennancenter.org/our-work/research-reports/artificial-intelligence-legislation-tracker"
            />
            <Stat
              n="½"
              body="House committee staff today versus 1980, as policy complexity has grown."
              source="R Street / Drutman coalition letter (2015)"
              href="https://www.rstreet.org/commentary/congress-must-invest-in-its-own-capacity-again/"
            />
          </div>
        </section>

        {/* HOW IT WORKS */}
        <section className="land-section">
          <div className="land-section-label mono">
            <span>How it works</span>
          </div>
          <div className="land-pillars">
            <Pillar
              title="Mechanically extracted"
              body="Definitions, amendments, and citations are pulled from the bill XML directly. No model paraphrases the law before you read it."
            />
            <Pillar
              title="Verbatim text, synced"
              body="Click a citation; the matching span lights up in the bill text. If the substring can't be located, the highlight degrades to scroll — it never invents one."
            />
            <Pillar
              title="Honest unknowns"
              body="If the corpus does not contain an answer, polilabs says so. No paraphrase, no inference, no plausible-sounding completion."
            />
          </div>
        </section>

        {/* WHAT'S IN THE CORPUS */}
        <section className="land-section">
          <div className="land-section-label mono">
            <span>What's in the corpus</span>
            <span className="land-section-tag mono">v1 · 118th–119th Congress</span>
          </div>
          <div className="land-corpus-grid">
            <div className="land-corpus-cell">
              <b>{c.bills.toLocaleString()}</b>
              <span>bills</span>
            </div>
            <div className="land-corpus-cell">
              <b>{c.sections.toLocaleString()}</b>
              <span>sections</span>
            </div>
            <div className="land-corpus-cell">
              <b>{c.defined_terms.toLocaleString()}</b>
              <span>defined terms</span>
            </div>
            <div className="land-corpus-cell">
              <b>{c.external_citations.toLocaleString()}</b>
              <span>external citations</span>
            </div>
          </div>
        </section>

        {/* CTA REPRISE */}
        <section className="land-cta-band">
          <div className="land-cta-band-copy">
            <div className="land-cta-band-h">Open the corpus.</div>
            <div className="land-cta-band-sub">
              Ask a question. Read what the bill actually says.
            </div>
          </div>
          <button type="button" className="land-cta" onClick={onOpenWorkspace}>
            Open the workspace <span aria-hidden="true">→</span>
          </button>
        </section>

        <footer className="land-foot">
          <span className="mono">
            polilabs · {c.bills} bills · 118th–119th Congress · citation-accurate, no hallucination
          </span>
        </footer>
      </main>
    </div>
  );
}

window.Landing = Landing;
