/* global React */

// Polilabs — Landing page. Two-stage hero:
//
//   1. headline — "Accelerating policy research." slides in from the
//                 right edge with an accelerating cubic-bezier and
//                 exits off the left edge over ~3 seconds. Single
//                 line, no wrap.
//   2. diagram  — once the headline has exited, an SVG diagram fades
//                 in node-by-node showing one bill (S. 4664, the DOE
//                 AI Act) connected to two of its real defined terms
//                 and two of its real external statute citations.
//                 Color encodes node TYPE — bill, definition,
//                 external citation — not chamber. Sits free on the
//                 cream canvas (no border, no panel).
//
// Below the hero: by-the-numbers (with each number linking to its
// primary source), how-it-works, corpus aggregates, CTA reprise.
//
// Data comes from web-design-a/landing-graph.json, regenerated by
// scripts/build_landing_graph.py — including the `hero` block with
// the focused diagram's real corpus connections.

const { useState, useEffect, useRef } = React;

// ── TypedHeadline ──────────────────────────────────────────────────────
// "Accelerating policy research." types out one character at a time at
// a constant cadence (~85ms per character). Single line — the font
// size is clamped in CSS so the phrase never wraps. After typing
// completes, the cursor lingers briefly, then onDone fires so the
// hero can swap in the diagram stage.
function TypedHeadline({ text, onDone, charMs = 85, holdMs = 750 }) {
  const [shown, setShown] = useState(0);
  const onDoneRef = useRef(onDone);
  onDoneRef.current = onDone;
  const fired = useRef(false);

  useEffect(() => {
    if (shown < text.length) {
      const id = setTimeout(() => setShown(shown + 1), charMs);
      return () => clearTimeout(id);
    }
    if (!fired.current) {
      fired.current = true;
      const id = setTimeout(() => {
        onDoneRef.current && onDoneRef.current();
      }, holdMs);
      return () => clearTimeout(id);
    }
  }, [shown, text.length, charMs, holdMs]);

  const done = shown >= text.length;
  return (
    <h1 className="land-typed-h">
      <span className="land-typed-text">{text.slice(0, shown)}</span>
      <span className={"land-typed-caret " + (done ? "is-done" : "")} aria-hidden="true">|</span>
    </h1>
  );
}

// ── HeroDiagram ────────────────────────────────────────────────────────
// SVG with five hand-positioned nodes around a central bill. Nodes
// fade and scale in one at a time with a small stagger; edges draw
// after their endpoint nodes appear. No border, no background panel
// — sits on the cream canvas.
function HeroDiagram({ hero, width = 1000, height = 560 }) {
  const [step, setStep] = useState(0); // 0 = nothing yet; 1..5 = nodes; 6+ = edges
  const timersRef = useRef([]);

  useEffect(() => {
    if (!hero) return;
    // Sequenced reveal: bill, then top, right, left, bottom, then edges.
    const cues = [120, 380, 640, 900, 1160, 1420];
    cues.forEach((t, i) => {
      const id = setTimeout(() => setStep(i + 1), t);
      timersRef.current.push(id);
    });
    return () => {
      timersRef.current.forEach(clearTimeout);
      timersRef.current = [];
    };
  }, [hero]);

  if (!hero || !hero.bill) {
    return <div className="land-diagram-empty mono">corpus unavailable</div>;
  }

  // ── layout: bill in the center, four satellites in a + ──────────
  // Coordinates are within the SVG viewBox; the viewBox scales to
  // whatever real CSS width the parent gives us.
  const W = width, H = height;
  const cx = W / 2, cy = H / 2;
  const bill = { x: cx, y: cy, w: 260, h: 116 };
  // satellite positions: (top, right, bottom, left)
  const top    = { x: cx,        y: 70,    w: 220, h: 60 };
  const right  = { x: W - 130,   y: cy,    w: 220, h: 60 };
  const bottom = { x: cx,        y: H - 70,w: 220, h: 60 };
  const left   = { x: 130,       y: cy,    w: 220, h: 60 };

  const defs = hero.definitions || [];
  const cites = hero.citations || [];
  // We render at most 2 defs + 2 cites in the four satellite slots,
  // arranging defs at top and left (the "extracted-from" side), cites
  // at right and bottom (the "reaches-into" side).
  const slots = [
    { pos: top,    node: defs[0],  type: "def",  edge: "defines" },
    { pos: right,  node: cites[0], type: "cite", edge: "cites" },
    { pos: bottom, node: cites[1], type: "cite", edge: "cites" },
    { pos: left,   node: defs[1],  type: "def",  edge: "defines" },
  ];

  // Label per node
  const labelFor = (slot) => {
    if (!slot.node) return null;
    if (slot.type === "def") return `"${slot.node.term}"`;
    return slot.node.label;
  };
  const subFor = (slot) => slot.type === "def" ? "definition" : "U.S. Code";

  // Draw a connector line between two rect-shaped nodes; the line
  // stops at the node edges, not the centers, so the heads don't
  // poke into the boxes.
  const connector = (a, b) => {
    const dx = b.x - a.x, dy = b.y - a.y;
    const ang = Math.atan2(dy, dx);
    const ax = a.x + Math.cos(ang) * (Math.abs(Math.cos(ang)) * a.w/2 + Math.abs(Math.sin(ang)) * a.h/2) * 0.92;
    const ay = a.y + Math.sin(ang) * (Math.abs(Math.cos(ang)) * a.w/2 + Math.abs(Math.sin(ang)) * a.h/2) * 0.92;
    const bx = b.x - Math.cos(ang) * (Math.abs(Math.cos(ang)) * b.w/2 + Math.abs(Math.sin(ang)) * b.h/2) * 0.92;
    const by = b.y - Math.sin(ang) * (Math.abs(Math.cos(ang)) * b.w/2 + Math.abs(Math.sin(ang)) * b.h/2) * 0.92;
    return { ax, ay, bx, by, mx: (ax + bx) / 2, my: (ay + by) / 2 };
  };

  const renderNode = (g, label, sub, kind, isOn) => {
    const cls = "land-node land-node-" + kind + (isOn ? " is-on" : "");
    const lines = wrapText(label, kind === "bill" ? 22 : 24);
    const lineH = kind === "bill" ? 19 : 16;
    const subY = g.y + g.h / 2 - 12;
    return (
      <g className={cls} key={kind + "-" + g.x + "-" + g.y}>
        <rect
          x={g.x - g.w / 2}
          y={g.y - g.h / 2}
          width={g.w}
          height={g.h}
          rx={kind === "bill" ? 10 : 8}
          className="land-node-rect"
        />
        {lines.map((line, i) => (
          <text
            key={i}
            x={g.x}
            y={g.y - (lines.length - 1) * lineH / 2 + i * lineH - (sub ? 8 : 2)}
            textAnchor="middle"
            className="land-node-label"
          >{line}</text>
        ))}
        {sub && (
          <text
            x={g.x}
            y={subY}
            textAnchor="middle"
            className="land-node-sub mono"
          >{sub}</text>
        )}
      </g>
    );
  };

  return (
    <div className="land-diagram-wrap">
      <svg
        className="land-diagram"
        viewBox={`0 0 ${W} ${H}`}
        preserveAspectRatio="xMidYMid meet"
        role="img"
        aria-label={`Anatomy of ${hero.bill.ref}: a bill with its definitions and cited statutes.`}
      >
        {/* edges first so the boxes overlap them cleanly */}
        {slots.map((slot, i) => {
          if (!slot.node) return null;
          const c = connector(bill, slot.pos);
          const edgeOn = step >= 6;
          return (
            <g key={"e-" + i} className={"land-edge " + (edgeOn ? "is-on" : "")}>
              <line
                x1={c.ax} y1={c.ay} x2={c.bx} y2={c.by}
                className="land-edge-line"
              />
              <text
                x={c.mx}
                y={c.my - 6}
                textAnchor="middle"
                className="land-edge-label mono"
              >{slot.edge}</text>
            </g>
          );
        })}

        {/* bill node */}
        {renderNode(
          bill,
          hero.bill.ref + " — " + hero.bill.label,
          // The Kùzu sponsor field repeats the (party-state) tag
          // ("Sen. Manchin, Joe, III [I-WV] (I-WV)") — drop the
          // duplicate bracketed form before showing it.
          (hero.bill.sponsor || "").replace(/\s*\[[^\]]+\]\s*/, " ").trim(),
          "bill",
          step >= 1,
        )}

        {/* satellites */}
        {slots.map((slot, i) => {
          if (!slot.node) return null;
          return (
            <React.Fragment key={"n-" + i}>
              {renderNode(
                slot.pos,
                labelFor(slot),
                subFor(slot),
                slot.type,
                step >= i + 2,
              )}
            </React.Fragment>
          );
        })}
      </svg>

      <div className="land-diagram-legend mono">
        <span className="leg-item"><span className="leg-swatch leg-bill" /> bill</span>
        <span className="leg-item"><span className="leg-swatch leg-def" /> definition</span>
        <span className="leg-item"><span className="leg-swatch leg-cite" /> U.S. Code</span>
        <span className="leg-hint">real connections drawn from {hero.bill.ref}</span>
      </div>
    </div>
  );
}

// Wrap a string into ≤ width characters per line, breaking at word
// boundaries. Tiny helper so the SVG node text fits inside its box.
function wrapText(s, width) {
  const words = String(s || "").split(/\s+/);
  const lines = [];
  let cur = "";
  for (const w of words) {
    if (!cur) { cur = w; continue; }
    if ((cur + " " + w).length <= width) cur += " " + w;
    else { lines.push(cur); cur = w; }
  }
  if (cur) lines.push(cur);
  // limit to 3 lines max with ellipsis on the last one
  if (lines.length > 3) {
    const head = lines.slice(0, 2);
    let tail = lines.slice(2).join(" ");
    if (tail.length > width - 1) tail = tail.slice(0, width - 1) + "…";
    return [...head, tail];
  }
  return lines;
}

// ── Stat tile (unchanged from v2) ────────────────────────────────────
function Stat({ n, body, source, href, caveat }) {
  return (
    <div className="land-stat">
      <a
        className="land-stat-n"
        href={href}
        target="_blank"
        rel="noopener noreferrer"
        title={`Source: ${source}`}
        aria-label={`${n}. ${body} Source: ${source}.`}
      >
        <span className="land-stat-n-text">{n}</span>
        <span className="land-stat-arrow" aria-hidden="true">↗</span>
      </a>
      <div className="land-stat-body">{body}</div>
      {caveat && <div className="land-stat-caveat mono">{caveat}</div>}
    </div>
  );
}

function Pillar({ title, body }) {
  return (
    <div className="land-pillar">
      <div className="land-pillar-title">{title}</div>
      <p className="land-pillar-body">{body}</p>
    </div>
  );
}

// ── Landing ──────────────────────────────────────────────────────────────
function Landing({ user, onOpenWorkspace, onSignIn, onSignOut }) {
  const [graphData, setGraphData] = useState(null);
  const [hero, setHero] = useState(null);
  const [corpus, setCorpus] = useState(null);
  const [loadError, setLoadError] = useState(false);

  // Hero stage machine: 'headline' → 'diagram'. The reveal of each
  // diagram node is its own internal stagger inside HeroDiagram.
  const [stage, setStage] = useState("headline");

  useEffect(() => {
    let cancelled = false;
    fetch("landing-graph.json")
      .then((r) => {
        if (!r.ok) throw new Error(`HTTP ${r.status}`);
        return r.json();
      })
      .then((j) => {
        if (cancelled) return;
        setGraphData(j.graph);
        setHero(j.hero);
        setCorpus(j.corpus);
      })
      .catch(() => { if (!cancelled) setLoadError(true); });
    return () => { cancelled = true; };
  }, []);

  const c = corpus || { bills: 191, sections: 29616, defined_terms: 1241, external_citations: 646 };

  return (
    <div className="land">
      <header className="land-header">
        <div className="land-brand">polilabs</div>
        <nav className="land-nav">
          {user ? (
            <React.Fragment>
              <span className="land-user mono">{user.email}</span>
              <button type="button" className="land-link" onClick={onSignOut}>
                Sign out
              </button>
            </React.Fragment>
          ) : (
            <button type="button" className="land-link" onClick={onSignIn}>
              Sign in
            </button>
          )}
        </nav>
      </header>

      <main className="land-main">
        {/* HERO — sliding headline → SVG anatomy diagram */}
        <section className={"land-hero land-hero-stage-" + stage}>
          {stage === "headline" && (
            <TypedHeadline
              text="Accelerating policy research."
              onDone={() => setStage("diagram")}
            />
          )}

          {stage === "diagram" && (
            <div className="land-stage">
              <div className="land-diagram-container">
                {hero ? (
                  <HeroDiagram hero={hero} />
                ) : (
                  <div className="land-diagram-empty mono">
                    {loadError ? "graph data unavailable" : "loading corpus…"}
                  </div>
                )}
              </div>
              <p className="land-lede">
                Citation-accurate research instrument for U.S. federal
                AI-governance legislation. Every answer grounded in
                verbatim bill text. If it is not in the bill, polilabs
                does not say it.
              </p>
              <div className="land-cta-row">
                <button type="button" className="land-cta" onClick={onOpenWorkspace}>
                  Open the workspace <span aria-hidden="true">→</span>
                </button>
                <div className="land-corpus mono">
                  <b>{c.bills}</b>&nbsp;bills
                  <span className="land-dot">·</span>
                  <b>118th–119th</b>&nbsp;Congress
                </div>
              </div>
            </div>
          )}
        </section>

        {/* BY THE NUMBERS — each number is itself the source link */}
        <section className="land-section land-stats-section">
          <div className="land-section-label mono">
            <span>By the numbers</span>
            <span className="land-section-tag mono">
              click any figure for the primary source
            </span>
          </div>
          <div className="land-stats-grid">
            <Stat
              n="19,315"
              body="bills introduced in the 118th Congress; 3% became law."
              source="GovTrack, Statistics and Historical Comparison"
              href="https://www.govtrack.us/congress/bills/statistics"
            />
            <Stat
              n="9×"
              body="denser legislation per enacted law than in 1955."
              source="Brookings Vital Statistics on Congress, via Pew (2021)"
              href="https://www.pewresearch.org/short-reads/2021/01/21/nothing-lame-about-this-lame-duck-116th-congress-had-busiest-post-election-session-in-recent-history/"
            />
            <Stat
              n="34%"
              body="of legal queries hallucinated by Westlaw's AI-Assisted Research, despite vendor 'hallucination-free' claims."
              source="Magesh et al., Hallucination-Free? Stanford RegLab, J. Empirical Legal Studies 2024"
              href="https://dho.stanford.edu/wp-content/uploads/Legal_RAG_Hallucinations.pdf"
            />
            <Stat
              n="3.1 yrs"
              body="median Hill-staff tenure — roughly a third haven't served a full Congress."
              source="New America / Congressional Capacity Survey, 2021 (2019 data)"
              href="https://www.newamerica.org/insights/congressional-brain-drain/congressional-staffers-job-satisfaction-career-trajectories-and-compensation/"
            />
            <Stat
              n="84%"
              body="of senior Hill staff: 'we can't accomplish as much as we'd like.'"
              source="Congressional Management Foundation, State of the Congress 2024"
              href="https://www.congressfoundation.org/s/cmf-state-of-the-congress-2024.pdf"
              caveat="n = 138, 5% response rate"
            />
            <Stat
              n="$34 : $1"
              body="corporate vs. labor + public-interest lobbying ratio."
              source="Drutman, The Business of America is Lobbying (Oxford, 2015); summary at New America"
              href="https://www.newamerica.org/insights/there-wasnt-always-much-corporate-lobbying/"
              caveat="2015 figures"
            />
            <Stat
              n="150+"
              body="AI bills introduced in the 118th Congress; zero became law."
              source="Brennan Center for Justice, AI Legislation Tracker (2025)"
              href="https://www.brennancenter.org/our-work/research-reports/artificial-intelligence-legislation-tracker"
            />
            <Stat
              n="½"
              body="House committee staff today versus 1980, as policy complexity has grown."
              source="R Street / Drutman coalition letter (2015)"
              href="https://www.rstreet.org/commentary/congress-must-invest-in-its-own-capacity-again/"
            />
          </div>
        </section>

        {/* HOW IT WORKS */}
        <section className="land-section">
          <div className="land-section-label mono">
            <span>How it works</span>
          </div>
          <div className="land-pillars">
            <Pillar
              title="Mechanically extracted"
              body="Definitions, amendments, and citations are pulled from the bill XML directly. No model paraphrases the law before you read it."
            />
            <Pillar
              title="Verbatim text, synced"
              body="Click a citation; the matching span lights up in the bill text. If the substring can't be located, the highlight degrades to scroll — it never invents one."
            />
            <Pillar
              title="Honest unknowns"
              body="If the corpus does not contain an answer, polilabs says so. No paraphrase, no inference, no plausible-sounding completion."
            />
          </div>
        </section>

        {/* WHAT'S IN THE CORPUS */}
        <section className="land-section">
          <div className="land-section-label mono">
            <span>What's in the corpus</span>
            <span className="land-section-tag mono">v1 · 118th–119th Congress</span>
          </div>
          <div className="land-corpus-grid">
            <div className="land-corpus-cell">
              <b>{c.bills.toLocaleString()}</b>
              <span>bills</span>
            </div>
            <div className="land-corpus-cell">
              <b>{c.sections.toLocaleString()}</b>
              <span>sections</span>
            </div>
            <div className="land-corpus-cell">
              <b>{c.defined_terms.toLocaleString()}</b>
              <span>defined terms</span>
            </div>
            <div className="land-corpus-cell">
              <b>{c.external_citations.toLocaleString()}</b>
              <span>external citations</span>
            </div>
          </div>
        </section>

        {/* CTA REPRISE */}
        <section className="land-cta-band">
          <div className="land-cta-band-copy">
            <div className="land-cta-band-h">Open the corpus.</div>
            <div className="land-cta-band-sub">
              Ask a question. Read what the bill actually says.
            </div>
          </div>
          <button type="button" className="land-cta" onClick={onOpenWorkspace}>
            Open the workspace <span aria-hidden="true">→</span>
          </button>
        </section>

        <footer className="land-foot">
          <span className="mono">
            polilabs · {c.bills} bills · 118th–119th Congress · citation-accurate, no hallucination
          </span>
        </footer>
      </main>
    </div>
  );
}

window.Landing = Landing;
