"""polilabs agent-facing API.

See api/SPEC.md for the design contract. Implementations live in api/_impl.py
and are backed by data/polilabs.db (SQLite, FTS) + data/polilabs.kuzu (graph).

These primitives are the ONLY supported way for an agent to query the
corpus. Lower-level direct DB/file access is for ingestion and tooling,
not for agents.
"""
from __future__ import annotations

from ._impl import (
    corpus_coverage,
    count_bills,
    find_bills_amending,
    find_bills_by_outcome,
    find_bills_defining,
    find_definitions_of,
    get_amendments,
    get_amendments_targeting,
    get_bill,
    get_bill_votes,
    get_citation_graph,
    get_defined_terms,
    get_section,
    resolve_citation,
    search_corpus,
)
from .types import (
    AdjacencySummary,
    AgreementScore,
    Amendment,
    AmendmentOperationType,
    AmendmentsResult,
    AmendmentsTargetingResult,
    Bill,
    BillAmendmentSummary,
    BillDefinitionMatch,
    BillsAmendingResult,
    BillsByOutcomeResult,
    BillsDefiningResult,
    BillVersion,
    BillVotesResult,
    CountBucket,
    CountResult,
    FacetCoverage,
    OutcomeBillSummary,
    OutcomeEvent,
    TopicCoverage,
    VoteSummary,
    CitationEdge,
    CitationGraph,
    CitationType,
    CoverageReport,
    DefinedTerm,
    DefinedTermsResult,
    DefinitionAcrossCorpus,
    DefinitionScope,
    DefinitionsAcrossCorpusResult,
    DefinitionType,
    Provenance,
    ResolvedCitation,
    ResolvedRef,
    SearchHit,
    SearchResults,
    Section,
    SectionRef,
    SourceFreshness,
    Stream,
    StreamStatus,
    Tier,
)

__all__ = [
    "search_corpus",
    "get_bill",
    "get_section",
    "get_citation_graph",
    "get_defined_terms",
    "get_amendments",
    "get_amendments_targeting",
    "find_bills_defining",
    "find_bills_amending",
    "find_definitions_of",
    "resolve_citation",
    "corpus_coverage",
    "count_bills",
    "get_bill_votes",
    "find_bills_by_outcome",
    # types re-exported for callers
    "BillsByOutcomeResult",
    "BillVotesResult",
    "CountBucket",
    "CountResult",
    "FacetCoverage",
    "OutcomeBillSummary",
    "OutcomeEvent",
    "TopicCoverage",
    "VoteSummary",
    "AdjacencySummary",
    "AgreementScore",
    "Amendment",
    "AmendmentOperationType",
    "AmendmentsResult",
    "AmendmentsTargetingResult",
    "Bill",
    "BillAmendmentSummary",
    "BillDefinitionMatch",
    "BillsAmendingResult",
    "BillsDefiningResult",
    "BillVersion",
    "CitationEdge",
    "CitationGraph",
    "CitationType",
    "CoverageReport",
    "DefinedTerm",
    "DefinedTermsResult",
    "DefinitionAcrossCorpus",
    "DefinitionScope",
    "DefinitionsAcrossCorpusResult",
    "DefinitionType",
    "Provenance",
    "ResolvedCitation",
    "ResolvedRef",
    "SearchHit",
    "SearchResults",
    "Section",
    "SectionRef",
    "SourceFreshness",
    "Stream",
    "StreamStatus",
    "Tier",
]
